import{g as f,S as g,i as h,a as p,b as n,f as i,s as v,e as d,c as x,n as c,d as y,h as l,j as b,k as u}from"./assets/vendor.c031b8c0.js";const k="button";function m(t,o,e){t.style.setProperty(o,e)}function w(t,o){const e=f();e.style&&m(e,t,o||"")}function z(t){let o,e,a;return{c(){o=d("button"),e=x(),a=d("slot"),this.c=c,y(o,"role",k)},m(r,s){n(r,o,s),n(r,e,s),n(r,a,s)},p:c,i:c,o:c,d(r){r&&l(o),r&&l(e),r&&l(a)}}}function _(t,o,e){let{color:a=null}=o;return t.$$set=r=>{e(1,o=b(b({},o),u(r))),"color"in r&&e(0,a=r.color)},t.$$.update=()=>{{const{color:r}=o;w("color",r)}},o=u(o),[a]}class H extends g{constructor(o){super();this.shadowRoot.innerHTML=`<style>:host{font-family:var(
      --one-family,
      'Helvetica Neue',
      Helvetica,
      'PingFang SC',
      'Hiragino Sans GB',
      'Microsoft YaHei',
      '\u5FAE\u8F6F\u96C5\u9ED1',
      Arial,
      sans-serif
    );display:inline-flex;align-items:center;justify-content:center;position:relative;cursor:pointer;line-height:1;width:var(--one-width, initial);height:var(--one-height, 34px);padding:var(--one-padding, 0 1em);border:1px solid var(--one-border-color, rgba(0, 0, 0, 0.2));font-size:var(--one-font-size, 14px);box-shadow:0 2px 6px var(--one-box-shadow, #e1e5e8);color:var(--one-text-color, #2c3136);background-color:var(--one-background-color, #fff);border-radius:var(--one-border-radius, 00.25em);transition:color 0.3s var(--one-bezier, cubic-bezier(0.4, 0, 0.2, 1)),
      background-color 0.3s var(--one-bezier, cubic-bezier(0.4, 0, 0.2, 1)),
      opacity 0.3s var(--one-bezier, cubic-bezier(0.4, 0, 0.2, 1)),
      border-color 0.3s var(--one-bezier, cubic-bezier(0.4, 0, 0.2, 1))}button{background:none;outline:0;border:0;position:absolute;left:0;top:0;width:100%;height:100%;padding:0;user-select:none;cursor:pointer}:host([disabled]),:host([loading]){pointer-events:none;cursor:not-allowed;opacity:0.6}:host([disabled]:not([type])){background:rgba(0, 0, 0, 0.1)}:host(:not([disabled]):hover),:host(:not([disabled]):focus){border-color:rgba(0, 0, 0, 0.25);box-shadow:rgba(0, 0, 0, 0.25) 0 4px 12px}:host(:not([disabled]):active){border-color:rgba(0, 0, 0, 0.15);box-shadow:rgba(0, 0, 0, 0.06) 0 2px 4px;transform:translateY(0em)}:host(:not([disabled]):hover){border-color:transparent;transform:translateY(-0.25px)}:host([type='danger']){color:#fff;box-shadow:0 2px 6px var(--one-danger-box-shadow-color, #fd9b96);border-color:var(--one-danger-background-color, #e91e63);background-color:var(--one-danger-background-color, #e91e63)}:host([type='primary']){color:#fff;box-shadow:0 2px 6px var(--one-primary-box-shadow-color, #acb5f6);border-color:var(--one-primary-background-color, #6777ef);background-color:var(--one-primary-background-color, #6777ef)}:host([type='info']){color:#fff;box-shadow:0 2px 6px var(--one-info-box-shadow-color, #82d3f8);border-color:var(--one-info-background-color, #2196f3);background-color:var(--one-info-background-color, #2196f3)}:host([type='warning']){color:#fff;box-shadow:0 2px 6px var(--one-warning-box-shadow-color, #ffc473);border-color:var(--one-warning-background-color, #ffc107);background-color:var(--one-warning-background-color, #ffc107)}:host([type='success']){color:#fff;box-shadow:0 2px 6px var(--one-success-box-shadow-color, #a8f5b4);border-color:var(--one-success-background-color, #63ed7a);background-color:var(--one-success-background-color, #63ed7a)}:host([ghost]){background-color:var(--one-background-color, #fff)}:host([ghost][type='danger']){color:var(--one-danger-background-color, #e91e63)}:host([ghost][type='primary']){color:var(--one-primary-background-color, #6777ef)}:host([ghost][type='info']){color:var(--one-info-background-color, #2196f3)}:host([ghost][type='warning']){color:var(--one-warning-background-color, #ffc107)}:host([ghost][type='success']){color:var(--one-success-background-color, #63ed7a)}:host([dashed]){border-style:dashed;background-color:var(--one-background-color, #fff)}:host([dashed][type='primary']){color:var(--one-primary-background-color, #6777ef)}</style>`,h(this,{target:this.shadowRoot,props:p(this.attributes),customElement:!0},_,z,v,{color:0},null),o&&(o.target&&n(o.target,this,o.anchor),o.props&&(this.$set(o.props),i()))}static get observedAttributes(){return["color"]}get color(){return this.$$.ctx[0]}set color(o){this.$$set({color:o}),i()}}customElements.define("one-button",H);
